### ISSUE TITLE
Credential Verification Failure

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#473]
Occasionally credential verification can fail with a **Server Error (500)**.

This occurs when the `/credential/<Id>/verify` endpoint is hit repeatedly.  For example refreshing (`Ctrl-F5`) `https://orgbook-dev.pathfinder.gov.bc.ca/api/credential/100/verify` repeatedly will eventually trigger the error.

Controller (API) Error:
```
ERROR 2020-03-23 14:59:03,873 log 1 140347963328256 Internal Server Error: /api/credential/100/verify
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa5cc7ed7f0>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='agent-indy-cat', port=8024): Max retries exceeded with url: /present-proof/records/c26fd2d4-d4a1-45a5-8b50-44f75756ac8d (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa5cc7ed7f0>: Failed to establish a new connection: [Errno 113] No route to host',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/indy/api/v2/views/rest.py", line 268, in verify
    headers=settings.ADMIN_REQUEST_HEADERS,
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='agent-indy-cat', port=8024): Max retries exceeded with url: /present-proof/records/c26fd2d4-d4a1-45a5-8b50-44f75756ac8d (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa5cc7ed7f0>: Failed to establish a new connection: [Errno 113] No route to host',))
```

Agent Error:
```
2020-03-23 14:58:22,431 aries_cloudagent.transport.outbound.manager ERROR >>> Posting error: http://api-indy-cat:8080/agentcb/topic/present_proof/;  Re-queue failed message ...
```

**Comment by WadeBarnes** [comment]
Discovered when investigating; https://github.com/bcgov/TheOrgBook/issues/874

**Comment by WadeBarnes** [comment]
This one is not easy to reproduce.  I've been trying on an off for a while now without success (failure actually).

**Comment by ianco** [comment]
To me it looks like an error in the environment:

OSError: [Errno 113] No route to host

**Comment by swcurran** [comment]
Looks like this is different from TheOrgBook one.

**Comment by WadeBarnes** [comment]
Yes, this one is completely different.

**Comment by WadeBarnes** [comment]
@ianco, I have to agree, it does look that way.  I was hoping to get some more detailed logging.

**Comment by WadeBarnes** [comment]
Not having any luck reproducing.  Going to close this assuming this was an anomaly.
