### ISSUE TITLE
V3 api issues

### ISSUE THREAD

**Issue by ianco** [bcgov/aries-vcr#539]
/credential/{credential_id}/verify - fails

vcr-api_1      | json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
vcr-api_1      | ERROR 2020-07-22 17:27:06,151 log 7 139771271681792 Internal Server Error: /agentcb/topic/present_proof/
vcr-api_1      | Traceback (most recent call last):
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
vcr-api_1      |     response = get_response(request)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
vcr-api_1      |     response = self.process_exception_by_middleware(e, request)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
vcr-api_1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
vcr-api_1      |     return view_func(*args, **kwargs)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
vcr-api_1      |     return self.dispatch(request, *args, **kwargs)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
vcr-api_1      |     response = self.handle_exception(exc)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
vcr-api_1      |     self.raise_uncaught_exception(exc)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
vcr-api_1      |     raise exc
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
vcr-api_1      |     response = handler(request, *args, **kwargs)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/rest_framework/decorators.py", line 50, in handler
vcr-api_1      |     return func(*args, **kwargs)
vcr-api_1      |   File "/home/indy/agent_webhooks/views.py", line 70, in agent_callback
vcr-api_1      |     response = handle_presentations(state, message)
vcr-api_1      |   File "/home/indy/agent_webhooks/views.py", line 311, in handle_presentations
vcr-api_1      |     credentials = resp.json()
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/models.py", line 898, in json
vcr-api_1      |     return complexjson.loads(self.text, **kwargs)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/json/__init__.py", line 354, in loads
vcr-api_1      |     return _default_decoder.decode(s)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/json/decoder.py", line 342, in decode
vcr-api_1      |     raise JSONDecodeError("Extra data", s, end)
vcr-api_1      | json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
vcr-agent_1    | 2020-07-22 17:27:06,157 aries_cloudagent.transport.outbound.manager ERROR Outbound message could not be delivered

/search/topic returns 404 if no parameters are provided

/search/topic/{id} doesn't work (404 for any set of parameters) - remove

/search/credential/{id} doesn't work (404 for any set of parameters) - remove

/search/autocomplete - should return a source id and/or or credential id associated with the result
                       (v2 returns an id but I'm not sure an id for what)

/search/autocomplete/{id} fails with 500 error - remove

**Comment by ianco** [comment]
- Added additional attributes to `/search/autocomplete` response json
- Added error message to `/search/autocomplete` when required parameters are missing
- removed `/search/.../{id}` endpoints
- fixed `/credential/.../validate` endpoint
