### ISSUE TITLE
Posting errors with Aries VCR "base" build

### ISSUE THREAD

**Issue by ianco** [bcgov/aries-vcr#742]
Note that these errors occur with a base build `./manage build` but not with `THEME=bcgov ./manage build`

1.  Error when posting a credential:

```
vcr-api_1     | Exception occurred during processing of request from ('192.168.80.7', 49328)
vcr-api_1     | Traceback (most recent call last):
vcr-api_1     |   File "/usr/lib64/python3.9/socketserver.py", line 683, in process_request_thread
vcr-api_1     |     self.finish_request(request, client_address)
vcr-api_1     |   File "/usr/lib64/python3.9/socketserver.py", line 360, in finish_request
vcr-api_1     |     self.RequestHandlerClass(request, client_address, self)
vcr-api_1     |   File "/usr/lib64/python3.9/socketserver.py", line 747, in __init__
vcr-api_1     |     self.handle()
vcr-api_1     |   File "/opt/app-root/lib64/python3.9/site-packages/django/core/servers/basehttp.py", line 171, in handle
vcr-api_1     |     self.handle_one_request()
vcr-api_1     |   File "/opt/app-root/lib64/python3.9/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
vcr-api_1     |     self.raw_requestline = self.rfile.readline(65537)
vcr-api_1     |   File "/usr/lib64/python3.9/socket.py", line 704, in readinto
vcr-api_1     |     return self._sock.recv_into(b)
vcr-api_1     | ConnectionResetError: [Errno 104] Connection reset by peer
```

2.  Error when verifying a credential

```
vcr-api_1     | ERROR 2023-02-28 20:57:03,540 log 18 140223677711936 Internal Server Error: /api/v3/credential/261/verify/undefined
vcr-api_1     | Traceback (most recent call last):
vcr-api_1     |   File "/opt/app-root/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
vcr-api_1     |     response = get_response(request)
vcr-api_1     |   File "/opt/app-root/lib64/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
vcr-api_1     |     response = self.process_exception_by_middleware(e, request)
vcr-api_1     |   File "/opt/app-root/lib64/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
vcr-api_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
vcr-api_1     |   File "/opt/app-root/lib64/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
vcr-api_1     |     return view_func(*args, **kwargs)
vcr-api_1     |   File "/opt/app-root/lib64/python3.9/site-packages/rest_framework/viewsets.py", line 114, in view
vcr-api_1     |     return self.dispatch(request, *args, **kwargs)
vcr-api_1     |   File "/opt/app-root/lib64/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
vcr-api_1     |     response = self.handle_exception(exc)
vcr-api_1     |   File "/opt/app-root/lib64/python3.9/site-packages/rest_framework/views.py", line 465, in handle_exception
vcr-api_1     |     self.raise_uncaught_exception(exc)
vcr-api_1     |   File "/opt/app-root/lib64/python3.9/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
vcr-api_1     |     raise exc
vcr-api_1     |   File "/opt/app-root/lib64/python3.9/site-packages/rest_framework/views.py", line 502, in dispatch
vcr-api_1     |     response = handler(request, *args, **kwargs)
vcr-api_1     |   File "/opt/app-root/src/api/v3/views/rest.py", line 253, in post_verify
vcr-api_1     |     if presentation_state["state"] == "verified":
vcr-api_1     | KeyError: 'state'
```

**Comment by WadeBarnes** [comment]
@ianco, You were saying the credentials still show up even with the errors.  Is that correct?

**Comment by ianco** [comment]
> @ianco, You were saying the credentials still show up even with the errors. Is that correct?

Yes that's correct, the errors seem to happen *after* the cred exchange is finished
